AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      Handler: CreateThumbnail.handler
      Runtime: nodejs6.10
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
        MyUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref mikephoto
            Events: s3:ObjectCreated:*

  mikephoto:
    Type: AWS::S3::Bucket